### ISSUE TITLE
Issue 1. Remove comments on method selectIndex in ConsoleUI class

### ISSUE THREAD

**Issue by artem-maklashev** [dekorator-test/advansed-git#1]
Убрать комментирование в методе selectIndex  в классе ConsoleUI

**Comment by ElenaAgapitova** [comment]
in work

**Comment by ElenaAgapitova** [comment]
done

**Comment by ElenaAgapitova** [comment]
https://github.com/dekorator-test/advansed-git/pull/2

**Comment by ElenaAgapitova** [comment]
https://github.com/dekorator-test/advansed-git/pull/4

**Comment by artem-maklashev** [comment]
good job. take five
